# Generated by Django 3.0 on 2019-12-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResiterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('doj', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
