# Generated by Django 3.0 on 2019-12-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resitermodel',
            name='emailid',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
