# Generated by Django 3.0 on 2019-12-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_productmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='bprice',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pid',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
        ),
    ]
